# Generated by Django 5.1 on 2024-08-20 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию блога', null=True, upload_to='blogs/photo', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='blog',
            name='users',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
