# Generated by Django 5.1 on 2024-08-20 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_mailingattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingattempt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.newsletter', verbose_name='Настройки рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='service_response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ почтового сервиса'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.message', verbose_name='Сообщения'),
        ),
    ]
