# Generated by Django 5.1 on 2024-08-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_view_any_mailings', 'Can view any mailings'), ('can_disable_mailings', 'Can disable mailings'), ('can_view_the_list_of_service_users', 'Can view the list of service users'), ('can_block_users_of_the_service', 'Can block users of the service')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
